##Data Work

Imports

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

Drive mounting and database work

In [ ]:
from google.colab import drive

drive.mount('/content/drive')
data_directory = '/content/drive/MyDrive/CS/Datasets/combine.csv'
db = pd.read_csv(data_directory)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
db.head()

year            name firstname  ... nflgrade Unnamed: 26 Unnamed: 27
0  2015  Ameer Abdullah     Ameer  ...      5.9         NaN         NaN
1  2015  Nelson Agholor    Nelson  ...      5.6         NaN         NaN
2  2015       Jay Ajayi       Jay  ...      6.0         NaN         NaN
3  2015  Kwon Alexander      Kwon  ...      5.4         NaN         NaN
4  2015    Mario Alford     Mario  ...      5.3         NaN         NaN

[5 rows x 28 columns]

Add Labels (Output Values)



In [ ]:
db.position.values

array(['RB', 'WR', 'RB', ..., 'OT', 'DE', 'RB'], dtype=object)

In [ ]:
lables = []
for index, row in db.iterrows(): 
    if (row["position"]=='OLB' or row["position"]=='K' or row["position"]=='P' or row["position"]=='RB' or row["position"]=='WR' or row["position"]=='FS' or row["position"]=='TE'or row["position"]=='CB' or row["position"]=='LS' or row["position"]=='SS' or row["position"]=='FB' or row["position"]=='QB' or row["position"]=='P') :
      lables.append(1)
    else:
      lables.append(0)
 
    

print(lables)


[1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 

In [ ]:
db['labels'] = lables

In [ ]:
db.head()

year            name firstname  ... Unnamed: 26 Unnamed: 27 labels
0  2015  Ameer Abdullah     Ameer  ...         NaN         NaN      1
1  2015  Nelson Agholor    Nelson  ...         NaN         NaN      1
2  2015       Jay Ajayi       Jay  ...         NaN         NaN      1
3  2015  Kwon Alexander      Kwon  ...         NaN         NaN      1
4  2015    Mario Alford     Mario  ...         NaN         NaN      1

[5 rows x 29 columns]

Tinker with the data

In [ ]:
db=db[db.weight>110]

In [ ]:
db=db[db.fortyyd>1]

In [ ]:
db.head()

year            name firstname  ... Unnamed: 26 Unnamed: 27 labels
0  2015  Ameer Abdullah     Ameer  ...         NaN         NaN      1
1  2015  Nelson Agholor    Nelson  ...         NaN         NaN      1
2  2015       Jay Ajayi       Jay  ...         NaN         NaN      1
3  2015  Kwon Alexander      Kwon  ...         NaN         NaN      1
4  2015    Mario Alford     Mario  ...         NaN         NaN      1

[5 rows x 29 columns]

In [ ]:
from sklearn import preprocessing

le = preprocessing.LabelEncoder()
le.fit(db.college)
colleges = le.transform(db.college)
print(colleges)
db['college_num'] = colleges


[147 259  22 ... 100  66 275]


Data Preperation

In [ ]:
xdb = db[['heightinchestotal', 'weight', 'fortyyd',"college_num"]].copy()
ydb = db[['labels']].copy()
xdb.head()

heightinchestotal  weight  fortyyd  college_num
0               69.0     205     4.60          147
1               72.0     198     4.42          259
2               72.0     221     4.57           22
3               73.0     227     4.55          105
4               68.0     180     4.43          275

In [ ]:
ydb.head()

labels
0       1
1       1
2       1
3       1
4       1

Normalization

In [ ]:
for column in xdb.columns:
    xdb[column] = (xdb[column] - xdb[column].min()) / (xdb[column].max() - xdb[column].min()) 

##Neural Net Prep

Adding the Neural Network

Somehow this got worse between today and yesterday. Not rly sure how...

In [ ]:
# sigmoid function
def nonlin(x,deriv=False):
  if(deriv==True):
    return x*(1-x) #getting derivative if specified
  return 1/(1+np.exp(-x)) #mapped to sigmoid
 
# input dataset
X = np.array(xdb) #input

print(X)
 
# output dataset
y = np.array(ydb)

# seed random numbers to make calculation deterministic (based only on input and inital conditions)
np.random.seed(4)

# initialize weights randomly with mean 0
syn0 = 2*np.random.random((4,1)) - 1

print("initial weights:",syn0)
epochs = 100000
for iter in range(epochs):
# forward propagation
  l0 = X
  l1 = nonlin(np.dot(l0,syn0)) #maps dot product of weights and input data to sigmoid
 

# how much did we miss?
  l1_error = y - l1 #how far off the prediction is

# multiply how much we missed by the slope of the sigmoid at the values in l1
  l1_delta = l1_error * nonlin(l1,True) #finds derivative at sigmoid

# update weights
  syn0 += np.dot(l0.T,l1_delta) #weights changed by error (slope of sigmoid error function)

  if(iter%200==0): #prints the loss after every 100 epochs
    print("epoch:",iter,"/",epochs,"|","Loss:",l1_delta)

print("Output After Training:")
print(l1)
print()
print("0 values:")
np.count_nonzero(l1 < .5)

[[0.82894737 0.52741514 0.76033058 0.51398601]
 [0.86842105 0.50913838 0.73057851 0.90559441]
 [0.86842105 0.5691906  0.7553719  0.07692308]
 ...
 [0.94736842 0.86684073 0.92066116 0.34965035]
 [0.93421053 0.63446475 0.78016529 0.23076923]
 [0.81578947 0.52219321 0.74876033 0.96153846]]
initial weights: [[0.93405968]
 [0.0944645 ]
 [0.94536872]
 [0.42963199]]
epoch: 0 / 100000 | Loss: [[ 0.01827788]
 [ 0.01382636]
 [ 0.02305659]
 ...
 [-0.09322908]
 [-0.1063061 ]
 [ 0.01397748]]
epoch: 200 / 100000 | Loss: [[ 1.12641240e-119]
 [ 6.34701920e-133]
 [ 2.07756910e-108]
 ...
 [-2.03304403e-285]
 [-1.17270268e-241]
 [ 1.39104451e-133]]
epoch: 400 / 100000 | Loss: [[ 1.08437651e-119]
 [ 5.93564423e-133]
 [ 2.06577729e-108]
 ...
 [-1.93051970e-285]
 [-1.13332909e-241]
 [ 1.29551150e-133]]
epoch: 600 / 100000 | Loss: [[ 1.04391658e-119]
 [ 5.55100000e-133]
 [ 2.05405453e-108]
 ...
 [-1.83318288e-285]
 [-1.09528430e-241]
 [ 1.20655511e-133]]
epoch: 800 / 100000 | Loss: [[ 1.00497326e-119]
 [ 5.1

4946

In [ ]:
#check for 0 and 1 values in labels
print("1 values:")
np.count_nonzero(ydb > .5)

1 values:


3054

In [ ]:
print("0 values:")
np.count_nonzero(ydb < .5)

0 values:


1893

In [ ]:
#find the split that results in that many 0 and 1 values in l1
print("1 values in l1:")
np.count_nonzero(l1 > 1e-135)

1 values in l1:


1801

In [ ]:
print("0 values in l1:")
np.count_nonzero(l1 < 1e-135)

0 values in l1:


3146

In [ ]:
#Create newlabels
def layerlabels(y, split):
  newlabels = []
  for i in y:
    if i > split:
      newlabels.append(1)
    else:
      newlabels.append(0)
  return newlabels

In [ ]:
print(layerlabels(l1, 1e-135))
print(y)

[1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 

In [ ]:
#create an accuracy checker that takes in labels and newlabels and finds false positives, negatives, 
def accuracycheck(labels,predictions):
  correct = 0
  false_positives = 0
  false_negatives = 0
  for j in zip(labels,predictions):
    if int(j[0]) == j[1]:
      correct += 1
    if int(j[0]) > j[1]:
      false_positives +=1
    if int(j[0]) < j[1]:
      false_negatives +=1

  accuracy = correct/(correct+false_positives+false_negatives)
  print("False Positives:",false_positives)
  print("False Negatives:",false_negatives)
  print("Correct:",correct)
  print()
  print("Accuracy:", accuracy)
  return accuracy

In [ ]:
predictions = layerlabels(l1, 1e-42)

accuracycheck(lables, predictions)

False Positives: 3054
False Negatives: 2
Correct: 1891

Accuracy: 0.38225186982009296


0.38225186982009296

Corrected two layer network

In [ ]:
import numpy as np

def nonlin(x,deriv=False):
	if(deriv==True):
	    return x*(1-x)

	return 1/(1+np.exp(-x))
    
X = np.array(xdb)
                
y = np.array(ydb)

np.random.seed(6)

# randomly initialize our weights with mean 0
syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1

print("initial weights:",syn0)
epochs = 60000000

for j in range(epochs):

	# Feed forward through layers 0, 1, and 2
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))
    l2 = nonlin(np.dot(l1,syn1))

    # how much did we miss the target value?
    l2_error = y - l2
    
    if(j%5000==0): #prints the loss after every 100 epochs
      print("epoch:",j,"/",epochs,"|","Loss:",str(np.mean(np.abs(l2_error))))
        
    l2_delta = l2_error*nonlin(l2,True)
    l1_error = l2_delta.dot(syn1.T)

    l1_delta = l1_error * nonlin(l1,True)

    syn1 += l1.T.dot(l2_delta)
    syn0 += l0.T.dot(l1_delta)

print("Output After Training:")
print(l2)
print()
print("0 values:")
np.count_nonzero(l2 < .5)

initial weights: [[ 0.7857203  -0.33604039  0.64245825 -0.91660675]
 [-0.78468664  0.19010413  0.05963472 -0.16238514]
 [-0.3291843   0.24503886 -0.12371715  0.47176421]]
epoch: 0 / 60000000 | Loss: 0.4609940046508511
epoch: 5000 / 60000000 | Loss: 0.38136307397872665
epoch: 10000 / 60000000 | Loss: 0.38136307399239816
epoch: 15000 / 60000000 | Loss: 0.3813630740061209
epoch: 20000 / 60000000 | Loss: 0.38136307401989517
epoch: 25000 / 60000000 | Loss: 0.3813630740337213
epoch: 30000 / 60000000 | Loss: 0.38136307404759967
epoch: 35000 / 60000000 | Loss: 0.3813630740615305
epoch: 40000 / 60000000 | Loss: 0.3813630740755143
epoch: 45000 / 60000000 | Loss: 0.38136307408955117
epoch: 50000 / 60000000 | Loss: 0.3813630741036416
epoch: 55000 / 60000000 | Loss: 0.38136307411778597
epoch: 60000 / 60000000 | Loss: 0.3813630741319845
epoch: 65000 / 60000000 | Loss: 0.3813630741462376
epoch: 70000 / 60000000 | Loss: 0.3813630741605457
epoch: 75000 / 60000000 | Loss: 0.38136307417490906
epoch: 8000

KeyboardInterrupt: ignored

##Keras Work

In [ ]:
#Train and Test Split


In [ ]:
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.callbacks import EarlyStopping
from keras.constraints import maxnorm
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler



X = np.array(xdb)
                
y = np.array(ydb)

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state=20, stratify=y)

num_cols = X_train.shape[1]

model = Sequential()

model.add(Dense(60, input_shape=(num_cols,), activation='relu'))
model.add(Dense(60, activation='relu'))
model.add(Dense(120, activation='relu'))
model.add(Dense(60, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

print(model.summary())

Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_26 (Dense)            (None, 60)                300       
                                                                 
 dense_27 (Dense)            (None, 60)                3660      
                                                                 
 dense_28 (Dense)            (None, 40)                2440      
                                                                 
 dense_29 (Dense)            (None, 1)                 41        
                                                                 
Total params: 6,441
Trainable params: 6,441
Non-trainable params: 0
_________________________________________________________________
None


In [ ]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

early_stopping_monitor = EarlyStopping(patience=40)

print(X_train,y_train)

model.fit(X_train, y_train, epochs=2000, validation_split=0.3, batch_size=128, callbacks=[early_stopping_monitor], validation_data=(X_test, y_test))
model.evaluate(X_test, y_test)

[[0.89473684 0.63446475 0.77355372 0.83566434]
 [0.90789474 0.79112272 0.84132231 1.        ]
 [0.88157895 0.52741514 0.73553719 0.23776224]
 ...
 [0.92105263 0.78067885 0.84793388 0.62237762]
 [0.97368421 0.79895561 0.83966942 0.08391608]
 [0.88157895 0.64490862 0.78677686 0.03496503]] [[1]
 [0]
 [1]
 ...
 [0]
 [0]
 [1]]
Epoch 1/2000
22/22 [==============================] - 1s 11ms/step - loss: 0.1617 - accuracy: 0.9173 - val_loss: 0.1953 - val_accuracy: 0.9091
Epoch 2/2000
22/22 [==============================] - 0s 4ms/step - loss: 0.1661 - accuracy: 0.9148 - val_loss: 0.1927 - val_accuracy: 0.9141
Epoch 3/2000
22/22 [==============================] - 0s 4ms/step - loss: 0.1637 - accuracy: 0.9184 - val_loss: 0.1946 - val_accuracy: 0.9066
Epoch 4/2000
22/22 [==============================] - 0s 4ms/step - loss: 0.1627 - accuracy: 0.9173 - val_loss: 0.1868 - val_accuracy: 0.9116
Epoch 5/2000
22/22 [==============================] - 0s 4ms/step - loss: 0.1596 - accuracy: 0.9224 - val_l

[0.22841289639472961, 0.8929293155670166]